services:
  nginx:
    image: nginx
    restart: unless-stopped
    ports: 
      - "80:80"
    volumes:
      - /root/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nextjs
  
  nextjs:
    image: ghcr.io/j4nn1k/personal-website-preview:latest
    restart: unless-stopped
    ports:
      - "3000:3000"