name: Docker Image Preview

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Log in to the container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
   
    - name: Set repository name
      run: |
        echo "LOWERCASEREPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: docker/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ env.LOWERCASEREPO }}-preview
